# Generated by Django 2.0.13 on 2020-10-03 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_question', models.TextField(unique=True)),
                ('q_answer', models.CharField(max_length=50)),
                ('q_choice1', models.CharField(max_length=50)),
                ('q_choice2', models.CharField(max_length=50)),
                ('q_choice3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModelQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_number', models.IntegerField(choices=[(1, 'Quiz 1'), (2, 'Quiz 2'), (3, 'Quiz 3'), (4, 'Quiz 4'), (5, 'Quiz 5'), (6, 'Quiz 6')])),
            ],
        ),
        migrations.CreateModel(
            name='ModelTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100, unique=True)),
                ('topic_examples', models.TextField(null=True)),
                ('topic_slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='modelquiz',
            name='quiz_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelquiztopic', to='appquiz.ModelTopic'),
        ),
        migrations.AddField(
            model_name='modelquestion',
            name='q_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelquestionquiz', to='appquiz.ModelQuiz'),
        ),
        migrations.AddField(
            model_name='modelquestion',
            name='q_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelquestiontopic', to='appquiz.ModelTopic'),
        ),
    ]
